1. Import the numpy package under the name np (★☆☆)

In [5]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [6]:
print('Current version: ' + np.__version__)
print(np.show_config())


Current version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139810746332592
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
   

3. Create a null vector of size 10 (★☆☆)

In [7]:
array = np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array (★☆☆)

In [8]:
print("%d bytes" % (array.size * array.itemsize))

80 bytes


In [9]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

5. How to get the documentation of the numpy add function from the command line? (★☆☆)


6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [10]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])


8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
print(vector[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
vector_3 = np.arange(0,9)
vector_3 = vector_3.reshape(3,3)
vector_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

vector_3 = np.arange(0,9)
vector_3 = vector_3.reshape(3,3)
vector_3

In [14]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)