1. Import the numpy package under the name np (★☆☆)

In [5]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [6]:
print('Current version: ' + np.__version__)
print(np.show_config())


Current version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139810746332592
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
   

3. Create a null vector of size 10 (★☆☆)

In [7]:
array = np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array (★☆☆)

In [8]:
print("%d bytes" % (array.size * array.itemsize))

80 bytes


In [9]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

5. How to get the documentation of the numpy add function from the command line? (★☆☆)


6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [10]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])


8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
print(vector[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
vector_3 = np.arange(0,9)
vector_3 = vector_3.reshape(3,3)
vector_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

vector_3 = np.arange(0,9)
vector_3 = vector_3.reshape(3,3)
vector_3

In [14]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

11. Create a 3x3 identity matrix (★☆☆)

In [15]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆)

In [16]:
np.random.rand(3,3,3)

array([[[0.23707792, 0.54965512, 0.59276035],
        [0.0297516 , 0.28843609, 0.23455389],
        [0.07128636, 0.59188609, 0.53841672]],

       [[0.56104265, 0.18833692, 0.3929571 ],
        [0.20984054, 0.8520993 , 0.71834987],
        [0.79322391, 0.06087223, 0.77381031]],

       [[0.18248109, 0.4085559 , 0.51040452],
        [0.84588272, 0.11196434, 0.5759583 ],
        [0.91612776, 0.20406068, 0.22119651]]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [17]:
arr_1 = np.random.rand(10,10)
maximum = np.max(arr_1)
minimum = np.min(arr_1)
print(arr_1)
print("Maximum number of array: ", maximum)
print("Minimum number of array: ", minimum)

[[0.88792029 0.55571346 0.58439288 0.81601687 0.93895967 0.60108299
  0.78739368 0.34446354 0.38737617 0.96565065]
 [0.63077505 0.69097724 0.50156036 0.73175618 0.91365594 0.68090298
  0.9714576  0.8170249  0.3878734  0.11202937]
 [0.89920921 0.99885312 0.25225325 0.09827596 0.32626889 0.41804206
  0.21790947 0.12545721 0.78838697 0.86687246]
 [0.69015306 0.92180612 0.9167613  0.81841164 0.08168136 0.8238592
  0.84682571 0.03203557 0.73233372 0.04203795]
 [0.16152935 0.07098203 0.54819236 0.96648748 0.68838121 0.9665878
  0.64312517 0.3912216  0.54990284 0.03612489]
 [0.58107302 0.70104624 0.06062123 0.17402453 0.04675409 0.50058643
  0.67855638 0.12657409 0.93584738 0.38034052]
 [0.61652974 0.21979931 0.39135458 0.21774441 0.43959238 0.13908078
  0.55695398 0.73344448 0.92044895 0.97290107]
 [0.89688865 0.02090163 0.61928437 0.25872515 0.62068551 0.53727744
  0.02055955 0.30824812 0.02625057 0.00525597]
 [0.04318528 0.39964022 0.63372524 0.29435859 0.03385708 0.69361692
  0.05906993 0

14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
arr_2 = np.random.randn(30)
mean_value = np.mean(arr_2)
print("Array: ", arr_2)
print("Mean of array: ", mean_value)

Array:  [ 0.18051348  0.81630597  1.2139443   0.04791966 -0.25544166 -1.2732957
  1.1146142   2.30670332 -0.50613393  0.83695708 -0.93054452  0.20127004
  1.42494602 -0.75208826 -2.0820615  -0.43382376  2.3997119   2.47343935
 -1.39012024 -1.2325761   1.21031722 -0.61481961  0.09864299 -0.77635091
 -1.12052893  0.37163139  0.00849947 -0.49606049  0.56480458  0.27950839]
Mean of array:  0.12286279198603371


15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [19]:
sample_array = np.zeros((5,5))
sample_array[1:-1,1:-1] = 1
sample_array

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

16. How to add a border (filled with 0's) around an existing array? (★☆☆)


In [20]:
# This is not correct
change_Arr = np.pad(arr_1,pad_width=1,mode="constant",constant_values=0)
change_Arr

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.88792029, 0.55571346, 0.58439288, 0.81601687,
        0.93895967, 0.60108299, 0.78739368, 0.34446354, 0.38737617,
        0.96565065, 0.        ],
       [0.        , 0.63077505, 0.69097724, 0.50156036, 0.73175618,
        0.91365594, 0.68090298, 0.9714576 , 0.8170249 , 0.3878734 ,
        0.11202937, 0.        ],
       [0.        , 0.89920921, 0.99885312, 0.25225325, 0.09827596,
        0.32626889, 0.41804206, 0.21790947, 0.12545721, 0.78838697,
        0.86687246, 0.        ],
       [0.        , 0.69015306, 0.92180612, 0.9167613 , 0.81841164,
        0.08168136, 0.8238592 , 0.84682571, 0.03203557, 0.73233372,
        0.04203795, 0.        ],
       [0.        , 0.16152935, 0.07098203, 0.54819236, 0.96648748,
        0.68838121, 0.9665878 , 0.64312517, 0.3912216 , 0.54990284,
        0.03612489,

17. What is the result of the following expression? (★☆☆)

In [21]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)


In [22]:
checker_board = np.zeros((8,8),dtype="int")
checker_board[1::2,::2] = 1
checker_board[::2,1::2] = 1
checker_board

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?


In [23]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [24]:
a = np.array([0,1])
np.tile(a, (8,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])


22. Normalize a 5x5 random matrix (★☆☆)

In [25]:
array_arr = np.random.rand(5,5)
maxi,mini = array_arr.max(),array_arr.min()
array_arr = (array_arr - mini)/(maxi - mini)
array_arr

array([[0.97665366, 0.46497414, 0.        , 0.78922413, 0.60615707],
       [1.        , 0.15901549, 0.93128983, 0.20997022, 0.70396921],
       [0.47840266, 0.74966819, 0.44108792, 0.72422445, 0.64524875],
       [0.61063971, 0.29240508, 0.31360636, 0.89803838, 0.09335726],
       [0.99822771, 0.49428365, 0.16194915, 0.09817167, 0.88443314]])

23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [26]:
RGBA = np.dtype([("Red",np.uint8),("Blue",np.uint8),("Green",np.uint8),("Yellow",np.uint8)])
color = np.array((1,2,3,4),dtype=RGBA)
print(color['Red'],color['Yellow'],color['Green'])
type(color)

1 4 3


numpy.ndarray

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [27]:
arr1 = np.random.random((5,3))
arr2 = np.random.random((3,2))
print(arr1 @ arr2)
#     OR
np.dot(arr1,arr2)

[[1.84129662 0.77245883]
 [0.69293772 0.369204  ]
 [0.98526051 0.55418433]
 [1.2630431  0.5005329 ]
 [1.20831542 0.73311883]]


array([[1.84129662, 0.77245883],
       [0.69293772, 0.369204  ],
       [0.98526051, 0.55418433],
       [1.2630431 , 0.5005329 ],
       [1.20831542, 0.73311883]])

25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

26. What is the output of the following script? (★☆☆)

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [28]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [30]:
Z = np.arange(16)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
# Z<Z>Z -> This is not legal expression

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

In [32]:

np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_693/3343435198.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

29. How to round away from zero a float array ? (★☆☆)

In [33]:
arr = np.random.random((2,2))
print('Before rounding: ',arr)
arr1 = np.round(arr,2)
arr1

Before rounding:  [[0.14746158 0.33351341]
 [0.26787263 0.01813658]]


array([[0.15, 0.33],
       [0.27, 0.02]])

30. How to find common values between two arrays? (★☆☆)

In [34]:
arr1 = np.array([2,3,4])
arr2 = np.array([4,3,1])
print(arr1)
print(arr2)
print("Common values: ", np.intersect1d(arr1,arr2))

[2 3 4]
[4 3 1]
Common values:  [3 4]



31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [2]:
import numpy as np

np.seterr(all='ignore')


{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [3]:


# Get today's date
today = np.datetime64('today')

# Get yesterday's date
yesterday = today - np.timedelta64(1, 'D')

# Get tomorrow's date
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-02-14
Today: 2024-02-15
Tomorrow: 2024-02-16


34. How to get all the dates corresponding to the month of July 2016? (★★☆)


In [4]:


# Define start and end dates for July 2016
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')

# Generate range of dates for July 2016
dates_july_2016 = np.arange(start_date, end_date, dtype='datetime64[D]')

print("Dates corresponding to July 2016:")
print(dates_july_2016)


Dates corresponding to July 2016:
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [5]:
# Define arrays A, B, and C
A = np.ones(3) * 1
B = np.ones(3) * 2

# Compute ((A+B)*(-A/2)) in place without making a copy
np.add(A, B, out=B)
np.negative(A, out=A)
np.divide(A, 2, out=A)
result = np.multiply(A, B)

print("Result:", result)

Result: [-1.5 -1.5 -1.5]


36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [7]:
import numpy as np

# Generate a random array of positive numbers
random_array = np.random.rand(5) * 10  # Multiply by 10 for larger numbers

# Method 1: Using np.floor()
integer_part_floor = np.floor(random_array)

# Method 2: Using np.trunc()
integer_part_trunc = np.trunc(random_array)

# Method 3: Using type casting to int
integer_part_casting = random_array.astype(int)

# Method 4: Using np.astype()
integer_part_astype = random_array.astype(np.int)

# Display the results
print("Method 1 (np.floor()):", integer_part_floor)
print("Method 2 (np.trunc()):", integer_part_trunc)
print("Method 3 (type casting to int):", integer_part_casting)
print("Method 4 (np.astype()):", integer_part_astype)


AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [8]:
# Create an array with values ranging from 0 to 4
row_values = np.arange(5)

# Repeat the row_values array 5 times along the rows to form a 5x5 matrix
matrix_5x5 = np.tile(row_values, (5, 1))

# Display the resulting matrix
print(matrix_5x5)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [9]:
# Define the generator function
def generate_integers():
    for i in range(10):
        yield i

# Use the generator function to build an array
arr = np.fromiter(generate_integers(), dtype=int)

# Display the resulting array
print(arr)

[0 1 2 3 4 5 6 7 8 9]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [10]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
vector = np.linspace(0, 1, 12)[1:-1]

# Display the resulting vector
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]



40. Create a random vector of size 10 and sort it (★★☆)

In [11]:
# Create a random vector of size 10
random_vector = np.random.rand(10)

# Sort the random vector
sorted_vector = np.sort(random_vector)

# Display the sorted vector
print(sorted_vector)

[0.00731686 0.08515158 0.20993692 0.44048547 0.57752295 0.5787081
 0.58054734 0.65911964 0.84025516 0.99387645]


41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
nap.nansum()

42. Consider two random array A and B, check if they are equal (★★☆)

In [15]:
# Assuming A and B are two random arrays
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

# Check if A and B are equal
equal = np.array_equal(A, B)
print(equal)

False



43. Make an array immutable (read-only) (★★☆)

In [16]:
# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Make the array immutable
arr.flags.writeable = False

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [18]:
# Create a random 10x2 matrix representing cartesian coordinates
cartesian_coords = np.random.rand(10, 2)

# Convert cartesian coordinates to polar coordinates
x, y = cartesian_coords[:, 0], cartesian_coords[:, 1]
r = np.linalg.norm(cartesian_coords, axis=1)
theta = np.arctan2(y, x)

# Display polar coordinates
polar_coords = np.column_stack((r, theta))
print("Polar Coordinates:")
print(polar_coords)

Polar Coordinates:
[[0.65140075 0.3218955 ]
 [0.57489179 0.2384781 ]
 [0.81814215 0.24195821]
 [1.0213542  0.45385071]
 [0.76996337 0.1178604 ]
 [0.84259096 1.20359031]
 [0.49948262 0.81840154]
 [0.93451528 1.22855722]
 [1.10515958 0.45250692]
 [0.81926439 1.2889208 ]]



45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [19]:
# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random vector with the maximum value replaced by 0:")
print(random_vector)

Random vector with the maximum value replaced by 0:
[0.48127532 0.0648461  0.         0.16613001 0.13492793 0.90050153
 0.02819775 0.80015481 0.38395622 0.94989172]


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)

In [20]:
# Define the number of points in each dimension
n_points = 10

# Generate x and y coordinates covering the [0,1]x[0,1] area
x_coords = np.linspace(0, 1, n_points)
y_coords = np.linspace(0, 1, n_points)

# Create a meshgrid of x and y coordinates
X, Y = np.meshgrid(x_coords, y_coords)

# Stack the x and y coordinates into a structured array
structured_array = np.vstack((X.ravel(), Y.ravel())).T

print("Structured array with x and y coordinates covering [0,1]x[0,1]:")
print(structured_array)

Structured array with x and y coordinates covering [0,1]x[0,1]:
[[0.         0.        ]
 [0.11111111 0.        ]
 [0.22222222 0.        ]
 [0.33333333 0.        ]
 [0.44444444 0.        ]
 [0.55555556 0.        ]
 [0.66666667 0.        ]
 [0.77777778 0.        ]
 [0.88888889 0.        ]
 [1.         0.        ]
 [0.         0.11111111]
 [0.11111111 0.11111111]
 [0.22222222 0.11111111]
 [0.33333333 0.11111111]
 [0.44444444 0.11111111]
 [0.55555556 0.11111111]
 [0.66666667 0.11111111]
 [0.77777778 0.11111111]
 [0.88888889 0.11111111]
 [1.         0.11111111]
 [0.         0.22222222]
 [0.11111111 0.22222222]
 [0.22222222 0.22222222]
 [0.33333333 0.22222222]
 [0.44444444 0.22222222]
 [0.55555556 0.22222222]
 [0.66666667 0.22222222]
 [0.77777778 0.22222222]
 [0.88888889 0.22222222]
 [1.         0.22222222]
 [0.         0.33333333]
 [0.11111111 0.33333333]
 [0.22222222 0.33333333]
 [0.33333333 0.33333333]
 [0.44444444 0.33333333]
 [0.55555556 0.33333333]
 [0.66666667 0.33333333]
 [0.7777777

47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [21]:
# Define the arrays X and Y
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Calculate the differences between elements of X and Y
diffs = 1 / (X[:, np.newaxis] - Y)

# The Cauchy matrix C is constructed from the differences
C = diffs

print("Cauchy matrix C:")
print(C)

Cauchy matrix C:
[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [22]:


# Print minimum and maximum representable values for integer types
for dtype in np.sctypes['int']:
    info = np.iinfo(dtype)
    print(f"Integer type: {dtype}, Min: {info.min}, Max: {info.max}")

# Print minimum and maximum representable values for floating-point types
for dtype in np.sctypes['float']:
    info = np.finfo(dtype)
    print(f"Float type: {dtype}, Min: {info.min}, Max: {info.max}")


Integer type: <class 'numpy.int8'>, Min: -128, Max: 127
Integer type: <class 'numpy.int16'>, Min: -32768, Max: 32767
Integer type: <class 'numpy.int32'>, Min: -2147483648, Max: 2147483647
Integer type: <class 'numpy.int64'>, Min: -9223372036854775808, Max: 9223372036854775807
Float type: <class 'numpy.float16'>, Min: -65504.0, Max: 65504.0
Float type: <class 'numpy.float32'>, Min: -3.4028234663852886e+38, Max: 3.4028234663852886e+38
Float type: <class 'numpy.float64'>, Min: -1.7976931348623157e+308, Max: 1.7976931348623157e+308


/home/musbah/.local/lib/python3.9/site-packages/numpy/core/getlimits.py:542: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)


Float type: <class 'numpy.longdouble'>, Min: -inf, Max: inf


49. How to print all the values of an array? (★★☆)

In [23]:
# Create an array (replace this with your array)
arr = np.arange(20)

# Set print options to print all values without truncation
np.set_printoptions(threshold=np.inf)

# Print the array
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]



50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [24]:
# Example vector
vector = np.array([1, 3, 5, 7, 9])

# Given scalar
scalar = 6

# Find the index of the closest value
index = np.abs(vector - scalar).argmin()

# Get the closest value
closest_value = vector[index]

print("Closest value to", scalar, "in the vector:", closest_value)

Closest value to 6 in the vector: 5
