In [15]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [16]:
import numpy as np

In [17]:
print(np. __version__)

1.26.4


In [18]:
null_vector = np.zeros(10)

In [19]:
a = np.array([7,2,9,10])

In [20]:
a = (1,2,3)

In [21]:
a.shape

AttributeError: 'tuple' object has no attribute 'shape'

In [ ]:
a = 1,

In [ ]:
type(a)

tuple

In [ ]:
a = np.array([7,2,9,10])
a+2

In [ ]:
import pandas as pd

/tmp/ipykernel_841/4080736814.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [ ]:
data

array([[ 1. ,  5. , -0.1],
       [ 0. , -1. ,  6.5]])

In [ ]:
data.shape

(2, 3)

In [ ]:
data*10

array([[ 10.,  50.,  -1.],
       [  0., -10.,  65.]])

In [ ]:
data+data

array([[ 2. , 10. , -0.2],
       [ 0. , -2. , 13. ]])

In [ ]:
a = [1,2,3]
type

In [ ]:
data.size

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

/tmp/ipykernel_551/4080736814.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [ ]:
import pandas as pd

/tmp/ipykernel_524/4080736814.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [ ]:
#Define a dictionary   'x'

x = {'Name': ['Lukman', 'Aminu', 'Amina', 'Fatima'], 'ID' : [1, 2, 3, 4], 'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'], 'Salary': [100000, 80000, 50000, 60000] }

In [ ]:
#casting the dictionary to a DataFrame
df = pd.DataFrame(x)

#display the result df
df


Name  ID       Department  Salary
0  Lukman   1  Architect Group  100000
1   Aminu   2   Software Group   80000
2   Amina   3      Design Team   50000
3  Fatima   4   Infrastructure   60000

In [ ]:
#Retrieving the "ID" column and assigning it to a variable x
x = df['ID']
x

0    1
1    2
2    3
3    4
Name: ID, dtype: int64

In [ ]:
#check the type of x
type(x)

pandas.core.series.Series

In [ ]:
#Retrieving the department, Salary and ID columns and assigning it to a value

z = df [['Department', 'Salary',  'ID']]
z

Department  Salary  ID
0  Architect Group  100000   1
1   Software Group   80000   2
2      Design Team   50000   3
3   Infrastructure   60000   4