1. Import the numpy package under the name np (★☆☆)

In [5]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [6]:
print('Current version: ' + np.__version__)
print(np.show_config())


Current version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139810746332592
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
   

3. Create a null vector of size 10 (★☆☆)

In [7]:
array = np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array (★☆☆)

In [8]:
print("%d bytes" % (array.size * array.itemsize))

80 bytes


In [9]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

5. How to get the documentation of the numpy add function from the command line? (★☆☆)


6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [10]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])


8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
print(vector[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
vector_3 = np.arange(0,9)
vector_3 = vector_3.reshape(3,3)
vector_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

vector_3 = np.arange(0,9)
vector_3 = vector_3.reshape(3,3)
vector_3

In [14]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

11. Create a 3x3 identity matrix (★☆☆)

In [15]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆)

In [16]:
np.random.rand(3,3,3)

array([[[0.23707792, 0.54965512, 0.59276035],
        [0.0297516 , 0.28843609, 0.23455389],
        [0.07128636, 0.59188609, 0.53841672]],

       [[0.56104265, 0.18833692, 0.3929571 ],
        [0.20984054, 0.8520993 , 0.71834987],
        [0.79322391, 0.06087223, 0.77381031]],

       [[0.18248109, 0.4085559 , 0.51040452],
        [0.84588272, 0.11196434, 0.5759583 ],
        [0.91612776, 0.20406068, 0.22119651]]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [17]:
arr_1 = np.random.rand(10,10)
maximum = np.max(arr_1)
minimum = np.min(arr_1)
print(arr_1)
print("Maximum number of array: ", maximum)
print("Minimum number of array: ", minimum)

[[0.88792029 0.55571346 0.58439288 0.81601687 0.93895967 0.60108299
  0.78739368 0.34446354 0.38737617 0.96565065]
 [0.63077505 0.69097724 0.50156036 0.73175618 0.91365594 0.68090298
  0.9714576  0.8170249  0.3878734  0.11202937]
 [0.89920921 0.99885312 0.25225325 0.09827596 0.32626889 0.41804206
  0.21790947 0.12545721 0.78838697 0.86687246]
 [0.69015306 0.92180612 0.9167613  0.81841164 0.08168136 0.8238592
  0.84682571 0.03203557 0.73233372 0.04203795]
 [0.16152935 0.07098203 0.54819236 0.96648748 0.68838121 0.9665878
  0.64312517 0.3912216  0.54990284 0.03612489]
 [0.58107302 0.70104624 0.06062123 0.17402453 0.04675409 0.50058643
  0.67855638 0.12657409 0.93584738 0.38034052]
 [0.61652974 0.21979931 0.39135458 0.21774441 0.43959238 0.13908078
  0.55695398 0.73344448 0.92044895 0.97290107]
 [0.89688865 0.02090163 0.61928437 0.25872515 0.62068551 0.53727744
  0.02055955 0.30824812 0.02625057 0.00525597]
 [0.04318528 0.39964022 0.63372524 0.29435859 0.03385708 0.69361692
  0.05906993 0

14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
arr_2 = np.random.randn(30)
mean_value = np.mean(arr_2)
print("Array: ", arr_2)
print("Mean of array: ", mean_value)

Array:  [ 0.18051348  0.81630597  1.2139443   0.04791966 -0.25544166 -1.2732957
  1.1146142   2.30670332 -0.50613393  0.83695708 -0.93054452  0.20127004
  1.42494602 -0.75208826 -2.0820615  -0.43382376  2.3997119   2.47343935
 -1.39012024 -1.2325761   1.21031722 -0.61481961  0.09864299 -0.77635091
 -1.12052893  0.37163139  0.00849947 -0.49606049  0.56480458  0.27950839]
Mean of array:  0.12286279198603371
