In [1]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [3]:
import numpy as np

# Print the NumPy version
print("NumPy version:", np.__version__)

# Print the NumPy configuration
np.show_config()


NumPy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139810746332592
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    n

3. Create a null vector of size 10 (★☆☆)

In [4]:
array = np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array (★☆☆)

In [5]:
print("%d bytes" % (array.size * array.itemsize))

80 bytes


In [6]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

5. How to get the documentation of the numpy add function from the command line? (★☆☆)

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
print(vector[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
vector_3 = np.arange(0,9)
vector_3 = vector_3.reshape(3,3)
vector_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

vector_3 = np.arange(0,9)

In [11]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.rand(3,3,3)

array([[[0.75133133, 0.20457758, 0.57746832],
        [0.02644752, 0.91048648, 0.45389618],
        [0.03033756, 0.34597299, 0.97234919]],

       [[0.4143977 , 0.24479983, 0.64431564],
        [0.75956703, 0.44264984, 0.65243226],
        [0.22660402, 0.83971069, 0.33649305]],

       [[0.81648358, 0.98745791, 0.63057979],
        [0.42665742, 0.99929306, 0.9496242 ],
        [0.30569773, 0.14764879, 0.67682279]]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
arr_1 = np.random.rand(10,10)
maximum = np.max(arr_1)
minimum = np.min(arr_1)
print(arr_1)
print("Maximum number of array: ", maximum)
print("Minimum number of array: ", minimum)

[[0.95493371 0.70760505 0.21255653 0.30889964 0.93555716 0.01761683
  0.6292771  0.25001237 0.5494918  0.48024354]
 [0.34301483 0.42206955 0.71720039 0.76362902 0.58305874 0.63853484
  0.12841163 0.28363422 0.35932976 0.11587057]
 [0.23358558 0.82251216 0.42189914 0.3471397  0.32910446 0.48695338
  0.25657316 0.43617422 0.30244381 0.61356113]
 [0.90311987 0.88398889 0.69478312 0.98246753 0.07406888 0.80466079
  0.55207518 0.14619415 0.11983822 0.79012195]
 [0.87725737 0.57820418 0.24580576 0.97520048 0.78665542 0.18955706
  0.60869784 0.40402203 0.09546527 0.42996557]
 [0.71292672 0.52658222 0.20310325 0.62789611 0.89584172 0.42010056
  0.91534717 0.5829308  0.71921242 0.5513248 ]
 [0.03501703 0.52337777 0.09208968 0.03336782 0.78887743 0.634787
  0.74968803 0.55500671 0.84207129 0.79373099]
 [0.3911379  0.13341852 0.82389324 0.3070833  0.21569518 0.16850675
  0.27072358 0.35965021 0.38793231 0.91767425]
 [0.27950506 0.67341343 0.52528755 0.56377823 0.15806179 0.64175812
  0.22607266 0

14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
arr_2 = np.random.randn(30)
mean_value = np.mean(arr_2)
print("Array: ", arr_2)
print("Mean of array: ", mean_value)

Array:  [-0.05897671  0.50954901  1.68526146 -1.13322529  0.76984475 -0.53072247
 -1.34012105 -0.22268054  0.03811597  1.75546092 -0.8095014  -1.22985569
 -0.85454639 -0.57666366  2.35856752  0.61275301 -1.18263252  0.80399714
 -0.28358606  0.72676992 -0.40695959 -0.46820711 -0.26075505  0.95087007
  1.16097417 -0.7286581  -0.23196519  0.63809538  0.18566626  2.98910904]
Mean of array:  0.16219926002347748


15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
sample_array = np.zeros((5,5))
sample_array[1:-1,1:-1] = 1
sample_array

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
# This is not correct
change_Arr = np.pad(arr_1,pad_width=1,mode="constant",constant_values=0)
change_Arr

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.95493371, 0.70760505, 0.21255653, 0.30889964,
        0.93555716, 0.01761683, 0.6292771 , 0.25001237, 0.5494918 ,
        0.48024354, 0.        ],
       [0.        , 0.34301483, 0.42206955, 0.71720039, 0.76362902,
        0.58305874, 0.63853484, 0.12841163, 0.28363422, 0.35932976,
        0.11587057, 0.        ],
       [0.        , 0.23358558, 0.82251216, 0.42189914, 0.3471397 ,
        0.32910446, 0.48695338, 0.25657316, 0.43617422, 0.30244381,
        0.61356113, 0.        ],
       [0.        , 0.90311987, 0.88398889, 0.69478312, 0.98246753,
        0.07406888, 0.80466079, 0.55207518, 0.14619415, 0.11983822,
        0.79012195, 0.        ],
       [0.        , 0.87725737, 0.57820418, 0.24580576, 0.97520048,
        0.78665542, 0.18955706, 0.60869784, 0.40402203, 0.09546527,
        0.42996557,

17. What is the result of the following expression? (★☆☆)

In [19]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [21]:
checker_board = np.zeros((8,8),dtype="int")
checker_board[1::2,::2] = 1
checker_board[::2,1::2] = 1
checker_board

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [22]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
a = np.array([0,1])
np.tile(a, (8,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
array_arr = np.random.rand(5,5)
maxi,mini = array_arr.max(),array_arr.min()
array_arr = (array_arr - mini)/(maxi - mini)
array_arr

array([[0.70615448, 0.32591315, 0.43393898, 0.        , 0.61454828],
       [0.19161461, 0.11522625, 0.07333447, 0.50996925, 0.04508478],
       [0.56453047, 0.25084102, 0.6476774 , 0.70985181, 0.39709704],
       [0.38768236, 0.94624875, 0.57001022, 0.44602358, 0.46247748],
       [1.        , 0.78613897, 0.01729577, 0.09587528, 0.5648891 ]])

23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [25]:
RGBA = np.dtype([("Red",np.uint8),("Blue",np.uint8),("Green",np.uint8),("Yellow",np.uint8)])
color = np.array((1,2,3,4),dtype=RGBA)
print(color['Red'],color['Yellow'],color['Green'])
type(color)

1 4 3


numpy.ndarray

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
arr1 = np.random.random((5,3))
arr2 = np.random.random((3,2))
print(arr1 @ arr2)
#     OR
np.dot(arr1,arr2)

[[0.78484838 1.53933726]
 [0.17340848 0.71947935]
 [0.89986753 1.19953026]
 [0.5922717  1.27842506]
 [0.42945943 0.55613904]]


array([[0.78484838, 1.53933726],
       [0.17340848, 0.71947935],
       [0.89986753, 1.19953026],
       [0.5922717 , 1.27842506],
       [0.42945943, 0.55613904]])

25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [2]:
def negate_elements(arr):
    for i in range(len(arr)):
        if  3 <= arr[i] <=  8:
            arr[i] *= -1
    return arr

# Example usage:
arr = [1,  2,  3,  4,  5,  6,  7,  8,  9,  10]
print("Original array:", arr)

negate_elements(arr)
print("Modified array:", arr)


Original array: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Modified array: [1, 2, -3, -4, -5, -6, -7, -8, 9, 10]


26. What is the output of the following script? (★☆☆)

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [28]:
Z = np.arange(16)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
# Z<Z>Z -> This is not legal expression

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

Z = np.arange(16)

In [29]:
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_27018/699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

29. How to round away from zero a float array ? (★☆☆)

In [30]:
arr = np.random.random((2,2))
print('Before rounding: ',arr)
arr1 = np.round(arr,2)
arr1

Before rounding:  [[0.45567604 0.82140474]
 [0.61569961 0.01409384]]


array([[0.46, 0.82],
       [0.62, 0.01]])

30. How to find common values between two arrays? (★☆☆)

In [31]:
arr1 = np.array([2,3,4])
arr2 = np.array([4,3,1])
print(arr1)
print(arr2)
print("Common values: ", np.intersect1d(arr1,arr2))

[2 3 4]
[4 3 1]
Common values:  [3 4]


31. How to ignore all numpy warnings (not recommended)? (★☆☆)

32. Is the following expressions true? (★☆☆)

In [32]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_27018/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [1]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.today().date()

# Get yesterday's date
yesterday = today - timedelta(days=1)

# Get tomorrow's date
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-02-21
Today: 2024-02-22
Tomorrow: 2024-02-23


34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [3]:
import calendar

# Define the month and year
month = 7  # July
year = 2016

# Get the number of days in the specified month
num_days = calendar.monthrange(year, month)[1]

# Generate all the dates for the month of July 2016
dates_july_2016 = [f"{year}-{month:02d}-{day:02d}" for day in range(1, num_days + 1)]

print("Dates corresponding to July 2016:")
print(dates_july_2016)

Dates corresponding to July 2016:
['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04', '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08', '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12', '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16', '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20', '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24', '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28', '2016-07-29', '2016-07-30', '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [3]:
def compute_in_place(A, B):
    # Compute A+B
    A += B
    # Compute -A/2
    A = -A /  2
    # Compute (A+B)*(-A/2)
    B = A * A
    return A, B

# Example usage:
A =  5
B =  3
print("Original values: A =", A, ", B =", B)

A, B = compute_in_place(A, B)
print("Modified values: A =", A, ", B =", B)


Original values: A = 5 , B = 3
Modified values: A = -4.0 , B = 16.0


36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [6]:

# Generate a random array of positive numbers
random_array = np.random.rand(5) * 10  # Example array of length 5 with values between 0 and 10

# Method 1: Using np.floor()
integer_part_floor = np.floor(random_array)

# Method 2: Using np.trunc()
integer_part_trunc = np.trunc(random_array)

# Method 3: Using astype(int)
integer_part_astype = random_array.astype(int)

# Method 4: Using modulus operator
integer_part_modulus = random_array - random_array % 1

# Print the results
print("Using np.floor():", integer_part_floor)
print("Using np.trunc():", integer_part_trunc)
print("Using astype(int):", integer_part_astype)
print("Using modulus operator:", integer_part_modulus)

Using np.floor(): [4. 4. 4. 8. 1.]
Using np.trunc(): [4. 4. 4. 8. 1.]
Using astype(int): [4 4 4 8 1]
Using modulus operator: [4. 4. 4. 8. 1.]


37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [7]:
# Create an array with values ranging from 0 to 4
row_values = np.arange(5)

# Use np.tile() to create the 5x5 matrix
matrix = np.tile(row_values, (5, 1))

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [8]:
# Define the generator function to generate 10 integers
def integer_generator():
    for i in range(10):
        yield i

# Use the generator function to create the array
arr = np.fromiter(integer_generator(), dtype=int)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [9]:
# Create a vector of size 10 with values ranging from 0 to 1 (both excluded)
vector = np.linspace(0, 1, 12, endpoint=False)[1:]

print(vector)

[0.08333333 0.16666667 0.25       0.33333333 0.41666667 0.5
 0.58333333 0.66666667 0.75       0.83333333 0.91666667]


40. Create a random vector of size 10 and sort it (★★☆)

In [10]:
# Create a random vector of size 10
random_vector = np.random.rand(10)

# Sort the random vector
sorted_vector = np.sort(random_vector)

print(sorted_vector)

[2.73392470e-04 4.44103688e-02 5.63770764e-01 5.71853385e-01
 6.01706908e-01 7.90184574e-01 8.00543462e-01 9.10881124e-01
 9.51097236e-01 9.94960923e-01]


41. How to sum a small array faster than np.sum? (★★☆)

In [11]:
# Small array
small_array = np.array([1, 2, 3, 4, 5])

# Sum using Python's built-in sum() function
sum_result = sum(small_array)

print(sum_result)

15


42. Consider two random array A and B, check if they are equal (★★☆)

In [12]:
# Generate two random arrays A and B
A = np.random.randint(0, 10, size=(3, 3))
B = np.random.randint(0, 10, size=(3, 3))

# Check if the arrays are equal
equal_arrays = np.array_equal(A, B)

print(equal_arrays)

False


43. Make an array immutable (read-only) (★★☆)

In [13]:
# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Make the array immutable
arr.flags.writeable = False

# Try to modify the array (will raise an error)
# arr[0] = 10  # Uncommenting this line will result in an error

print(arr)

[1 2 3 4 5]


44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [14]:
# Create a random 10x2 matrix representing Cartesian coordinates
cartesian_coords = np.random.rand(10, 2)

# Extract x and y coordinates
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]

# Convert to polar coordinates
r = np.hypot(x, y)  # Calculate radius
theta = np.arctan2(y, x)  # Calculate angle in radians

# Print polar coordinates
print("Polar Coordinates:")
for i in range(10):
    print(f"Point {i+1}: (r={r[i]}, theta={np.degrees(theta[i])}) degrees")

Polar Coordinates:
Point 1: (r=0.3730063785095398, theta=32.13382422118484) degrees
Point 2: (r=0.9682407985562836, theta=27.537343788612564) degrees
Point 3: (r=0.8597105061660639, theta=17.114672361983743) degrees
Point 4: (r=0.5092620559594707, theta=36.79411183569767) degrees
Point 5: (r=0.37480399504742873, theta=14.442310731345978) degrees
Point 6: (r=0.6814731352139524, theta=67.84067157831959) degrees
Point 7: (r=1.0225019576861272, theta=47.872966318149594) degrees
Point 8: (r=0.47261186898590407, theta=26.58886051734918) degrees
Point 9: (r=0.32791753181928385, theta=13.760050207339155) degrees
Point 10: (r=1.2614137420202076, theta=49.29574129694153) degrees


45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [15]:
# Step 1: Generate a random vector of size 10
random_vector = np.random.rand(10)

# Step 2: Find the maximum value in the vector
max_value = np.max(random_vector)

# Step 3: Replace the maximum value with 0
random_vector[random_vector == max_value] = 0

# Print the random vector after replacing the maximum value
print("Random vector with the maximum value replaced by 0:")
print(random_vector)

Random vector with the maximum value replaced by 0:
[0.         0.88002173 0.33193613 0.31310866 0.02014215 0.32480657
 0.37235511 0.4246427  0.62356781 0.75455949]


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)

In [16]:
# Step 1: Define the data type for the structured array
dtype = [('x', float), ('y', float)]

# Step 2: Generate x and y coordinates covering the [0,1]x[0,1] area
x_coords = np.linspace(0, 1, num=10)  # 10 points along the x-axis
y_coords = np.linspace(0, 1, num=10)  # 10 points along the y-axis

# Step 3: Create the structured array
structured_array = np.zeros((10, 10), dtype=dtype)
structured_array['x'], structured_array['y'] = np.meshgrid(x_coords, y_coords)

# Print the structured array
print("Structured array with x and y coordinates covering [0,1]x[0,1]:")
print(structured_array)

Structured array with x and y coordinates covering [0,1]x[0,1]:
[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.3333333

47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [17]:
# Example arrays X and Y
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Construct Cauchy matrix C
C = 1 / (X[:, np.newaxis] - Y)

# Print the Cauchy matrix
print("Cauchy matrix C:")
print(C)

Cauchy matrix C:
[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [18]:
# Integer types
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"Minimum value for {dtype}: {info.min}")
    print(f"Maximum value for {dtype}: {info.max}")

# Floating-point types
for dtype in [np.float16, np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"Minimum value for {dtype}: {info.min}")
    print(f"Maximum value for {dtype}: {info.max}")

Minimum value for <class 'numpy.int8'>: -128
Maximum value for <class 'numpy.int8'>: 127
Minimum value for <class 'numpy.int16'>: -32768
Maximum value for <class 'numpy.int16'>: 32767
Minimum value for <class 'numpy.int32'>: -2147483648
Maximum value for <class 'numpy.int32'>: 2147483647
Minimum value for <class 'numpy.int64'>: -9223372036854775808
Maximum value for <class 'numpy.int64'>: 9223372036854775807
Minimum value for <class 'numpy.float16'>: -65504.0
Maximum value for <class 'numpy.float16'>: 65504.0
Minimum value for <class 'numpy.float32'>: -3.4028234663852886e+38
Maximum value for <class 'numpy.float32'>: 3.4028234663852886e+38
Minimum value for <class 'numpy.float64'>: -1.7976931348623157e+308
Maximum value for <class 'numpy.float64'>: 1.7976931348623157e+308


49. How to print all the values of an array? (★★☆)

In [4]:
# Example array
arr = [1,  2,  3,  4,  5]

# Print all values of the array
for value in arr:
    print(value)


1
2
3
4
5


50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [20]:
# Example vector
vector = np.array([1, 3, 5, 7, 9])

# Given scalar
scalar = 6

# Calculate absolute difference
abs_diff = np.abs(vector - scalar)

# Find index of minimum absolute difference
closest_index = np.argmin(abs_diff)

# Find the closest value
closest_value = vector[closest_index]

print("Closest value to", scalar, "in the vector is:", closest_value)

Closest value to 6 in the vector is: 5


51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [21]:
# Define the data types for position and color
dtype_position = [('x', float), ('y', float)]
dtype_color = [('r', int), ('g', int), ('b', int)]

# Create the structured array
structured_array = np.zeros(1, dtype=[('position', dtype_position), ('color', dtype_color)])

# Assign values to the structured array
structured_array['position'] = (0.5, 0.7)  # Example position values
structured_array['color'] = (255, 0, 0)    # Example color values

print("Structured array representing position and color:")
print(structured_array)

Structured array representing position and color:
[((0.5, 0.7), (255, 0, 0))]


52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [22]:
# Create a random vector of shape (100, 2) representing coordinates
random_vector = np.random.rand(100, 2)

# Calculate point-by-point distances using numpy.linalg.norm
distances = np.linalg.norm(random_vector[:, None] - random_vector, axis=-1)

print("Point-by-point distances:")
print(distances)

Point-by-point distances:
[[0.         0.44324646 0.47311856 ... 0.97332995 0.16106212 0.26308493]
 [0.44324646 0.         0.03007184 ... 0.82172766 0.34655588 0.35890551]
 [0.47311856 0.03007184 0.         ... 0.81559797 0.37387121 0.3813712 ]
 ...
 [0.97332995 0.82172766 0.81559797 ... 0.         0.81710592 0.71075224]
 [0.16106212 0.34655588 0.37387121 ... 0.81710592 0.         0.10795439]
 [0.26308493 0.35890551 0.3813712  ... 0.71075224 0.10795439 0.        ]]


53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [23]:
# Create a float (32 bits) array
float_array = np.array([1.5, 2.7, 3.9], dtype=np.float32)

# Convert the float array to an integer (32 bits) array in place
float_array = float_array.astype(np.int32)

print("Integer (32 bits) array:")
print(float_array)

Integer (32 bits) array:
[1 2 3]


54. How to read the following file? (★★☆)
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [25]:
# Create a NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Iterate over the array elements and their indices
for index, value in np.ndenumerate(arr):
    print("Index:", index, "Value:", value)

Index: (0, 0) Value: 1
Index: (0, 1) Value: 2
Index: (0, 2) Value: 3
Index: (1, 0) Value: 4
Index: (1, 1) Value: 5
Index: (1, 2) Value: 6


56. Generate a generic 2D Gaussian-like array (★★☆)

In [15]:
import numpy as np

def generate_gaussian_array(size, sigma=1.0):
    """
    Generate a  2D Gaussian-like array.
    
    Parameters:
    - size: A tuple specifying the dimensions of the array (height, width).
    - sigma: The standard deviation of the Gaussian distribution.
    
    Returns:
    - A  2D NumPy array representing a Gaussian-like distribution.
    """
    # Create a grid of coordinates
    x, y = np.meshgrid(np.arange(size[1]), np.arange(size[0]))
    
    # Calculate the Gaussian function
    gaussian = np.exp(-((x - size[1] /   2) **   2 + (y - size[0] /   2) **   2) / (2 * sigma **   2))
    
    return gaussian

# Example usage
size = (100,   100)  #  100x100 array
sigma =   20  # Standard deviation
gaussian_array = generate_gaussian_array(size, sigma)

# Print the shape of the generated array
print("Shape of the Gaussian-like array:", gaussian_array.shape)

# Optionally, visualize the array using matplotlib
import matplotlib.pyplot as plt

plt.imshow(gaussian_array, cmap='gray')
plt.colorbar()
plt.title('2D Gaussian-like Array')
plt.show()


Shape of the Gaussian-like array: (100, 100)


ModuleNotFoundError: No module named 'matplotlib'

57. How to randomly place p elements in a 2D array? (★★☆)

In [27]:
def randomly_place_elements(array_2d, p, element):
    # Determine the shape of the array
    rows, cols = array_2d.shape
    
    # Calculate the total number of elements in the array
    total_elements = rows * cols
    
    # Calculate the number of elements to place
    num_elements_to_place = min(p, total_elements)
    
    # Generate random indices to place the elements
    random_indices = np.random.choice(total_elements, num_elements_to_place, replace=False)
    
    # Calculate row and column indices from the flattened index
    row_indices, col_indices = np.unravel_index(random_indices, (rows, cols))
    
    # Place the elements at the randomly generated indices
    array_2d[row_indices, col_indices] = element
    
    return array_2d

# Example usage
array_2d = np.zeros((5, 5))  # Example 5x5 array
p = 3  # Number of elements to place
element = 1  # Element to place
result_array = randomly_place_elements(array_2d, p, element)
print(result_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]


58. Subtract the mean of each row of a matrix (★★☆)

In [28]:
# Create a sample matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Compute the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row-wise means from each element of the matrix
result_matrix = matrix - row_means

print("Original Matrix:")
print(matrix)
print("\nSubtracting the mean of each row:")
print(result_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Subtracting the mean of each row:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


59. How to sort an array by the nth column? (★★☆)

In [29]:

# Create a sample array
array = np.array([[3, 6, 9],
                  [1, 4, 7],
                  [2, 5, 8]])

# Define the column index to sort by (zero-based index)
n = 1

# Get the indices that would sort the array along the nth column
sorted_indices = np.argsort(array[:, n])

# Rearrange the rows of the array according to the sorted indices
sorted_array = array[sorted_indices]

print("Original Array:")
print(array)
print("\nSorted by the nth column:")
print(sorted_array)

Original Array:
[[3 6 9]
 [1 4 7]
 [2 5 8]]

Sorted by the nth column:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


60. How to tell if a given 2D array has null columns? (★★☆)

In [30]:
# Create a sample 2D array with potential null columns
array = np.array([[1, 2, np.nan],
                  [4, np.nan, 6],
                  [7, 8, 9]])

# Check for NaN values in the array
nan_mask = np.isnan(array)

# Check if all elements in each column are NaN
null_columns = np.all(nan_mask, axis=0)

# Check if any column is a null column
if np.any(null_columns):
    print("The array has null columns.")
else:
    print("The array does not have null columns.")

print("Null columns:", null_columns)

The array does not have null columns.
Null columns: [False False False]


61. Find the nearest value from a given value in an array (★★☆)

In [31]:
def find_nearest(array, value):
    # Calculate the absolute difference between each element and the given value
    absolute_diff = np.abs(array - value)
    # Find the index of the minimum absolute difference
    idx = np.argmin(absolute_diff)
    # Retrieve the nearest value from the array
    nearest_value = array[idx]
    return nearest_value

# Example usage
array = np.array([1, 3, 5, 7, 9])
given_value = 6
nearest = find_nearest(array, given_value)
print("Nearest value to", given_value, "in the array:", nearest)

Nearest value to 6 in the array: 5


62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [32]:
# Create the two arrays
array1 = np.array([[1, 2, 3]])  # Shape (1,3)
array2 = np.array([[4], [5], [6]])  # Shape (3,1)

# Initialize the sum to zero
total_sum = 0

# Iterate over the arrays using nditer
it = np.nditer([array1, array2])
for x, y in it:
    total_sum += x + y

# Print the total sum
print("Sum of the two arrays:", total_sum)

Sum of the two arrays: 63


63. Create an array class that has a name attribute (★★☆)

In [33]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name=None):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

# Example usage:
arr = NamedArray([1, 2, 3], name="example_array")
print(arr)  # Output: [1 2 3]
print(arr.name)  # Output: example_array

[1 2 3]
example_array


64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [34]:
# Given vector
vector = np.array([0, 1, 2, 3, 4])

# Second vector containing indices
indices = np.array([1, 3, 1, 4])

# Add 1 to each element indexed by the second vector
np.add.at(vector, indices, 1)

print(vector)

[0 3 2 4 5]


65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)


66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [39]:
import numpy as np

# Assuming 'image' is your (w,h,3) image of dtype=ubyte
# Replace this with your actual image data
image = np.random.randint(0, 256, size=(10, 10, 3), dtype=np.uint8)

# Reshape the image to (w*h, 3) to treat each pixel as a separate color
pixels = np.reshape(image, (-1, 3))

# Convert the pixels array to a unique list of colors
unique_colors = np.unique(pixels, axis=0)

# Compute the number of unique colors
num_unique_colors = len(unique_colors)

print("Number of unique colors:", num_unique_colors)


Number of unique colors: 100


67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [40]:
# Assuming 'arr' is your four-dimensional array
# Replace this with your actual array data
arr = np.random.randint(0, 10, size=(2, 3, 4, 5))

# Get the sum over the last two axes (axis=-2 and axis=-1)
sum_last_two_axes = np.sum(arr, axis=(-2, -1))

print("Sum over the last two axes:")
print(sum_last_two_axes)

Sum over the last two axes:
[[ 98 104  94]
 [ 88  87 118]]


68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)

In [41]:
# Example vectors D and S
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
S = np.array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])  # Subset indices

# Find unique elements in S
unique_elements = np.unique(S)

# Initialize an empty list to store subset means
subset_means = []

# Iterate over unique elements
for elem in unique_elements:
    # Find indices where S equals the unique element
    subset_indices = np.where(S == elem)
    
    # Extract subset from D using subset_indices
    subset = D[subset_indices]
    
    # Compute mean of the subset and append to subset_means
    subset_mean = np.mean(subset)
    subset_means.append(subset_mean)

# Convert subset_means to numpy array
subset_means = np.array(subset_means)

print("Subset Means:", subset_means)

Subset Means: [1.5 3.5 5.5 7.5 9.5]


69. How to get the diagonal of a dot product? (★★★)

In [42]:

# Example matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Compute the dot product
dot_product = np.dot(A, B)

# Get the diagonal of the dot product
diagonal = np.diagonal(dot_product)

print("Diagonal of the dot product:", diagonal)

Diagonal of the dot product: [30 69 90]


70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [7]:
# Original vector
original_vector = [1,  2,  3,  4,  5]

# Build a new vector with  3 consecutive zeros interleaved between each value
new_vector = [item for value in original_vector for item in (value,  0,  0,  0)]

# Remove the trailing zeros
new_vector = new_vector[:-3]

print(new_vector)


[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]


71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [45]:
# Create arrays with the specified dimensions
array_3d = np.random.rand(5, 5, 3)  # Example 3D array
array_2d = np.random.rand(5, 5)     # Example 2D array

# Multiply the 3D array by the 2D array
result = array_3d * array_2d[:, :, None]

print("Resulting array shape:", result.shape)

Resulting array shape: (5, 5, 3)


72. How to swap two rows of an array? (★★★)

In [46]:
# Create a sample array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Swap rows 0 and 1
array[[0, 1]] = array[[1, 0]]

print("Swapped array:")
print(array)

Swapped array:
[[4 5 6]
 [1 2 3]
 [7 8 9]]


73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)

In [47]:
# Given set of 10 triplets describing 10 triangles
triplets = np.random.randint(0, 100, (10, 3, 2))

# Convert triplets to line segments
line_segments = triplets[:, :, :2].reshape(-1, 2)

# Sort the line segments to ensure consistency for comparison
sorted_segments = np.sort(line_segments, axis=1)

# Find the unique line segments
unique_segments, indices = np.unique(sorted_segments, axis=0, return_index=True)

# Output the unique line segments
print("Unique line segments composing all the triangles:")
print(unique_segments)

Unique line segments composing all the triangles:
[[ 0 79]
 [ 0 93]
 [ 4 41]
 [ 7 99]
 [ 9 21]
 [10 22]
 [12 42]
 [12 64]
 [14 78]
 [15 89]
 [15 93]
 [16 16]
 [17 91]
 [19 28]
 [23 43]
 [23 99]
 [28 90]
 [34 36]
 [35 91]
 [36 80]
 [41 44]
 [43 44]
 [48 92]
 [52 75]
 [63 86]
 [69 72]
 [73 89]
 [73 90]
 [78 95]
 [85 94]]


74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [48]:
# Given sorted array C corresponding to bincount
C = np.array([1, 2, 0, 3, 1, 0, 1])

# Calculate the length of array A
A_length = np.sum(C)

# Initialize array A with calculated length
A = np.empty(A_length, dtype=np.int64)

# Create an array of indices corresponding to counts in C
indices = np.arange(len(C))

# Repeat each index according to the count in C
repeated_indices = np.repeat(indices, C)

# Concatenate repeated indices to obtain array A
np.copyto(A, repeated_indices)

# Output array A
print("Array A such that np.bincount(A) == C:")
print(A)

Array A such that np.bincount(A) == C:
[0 1 1 3 3 3 4 6]


75. How to compute averages using a sliding window over an array? (★★★)

In [49]:
# Define the array and window size
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
window_size = 3

# Create a window of ones
window = np.ones(window_size)

# Compute the sliding window sum using numpy.convolve
window_sum = np.convolve(arr, window, mode='valid')

# Compute the averages
averages = window_sum / window_size

# Output the averages
print("Averages using a sliding window of size", window_size, ":")
print(averages)

Averages using a sliding window of size 3 :
[2. 3. 4. 5. 6. 7. 8. 9.]


76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [50]:
# Example one-dimensional array
Z = np.array([1, 2, 3, 4, 5, 6, 7])

# Initialize empty list for rows
rows = []

# Iterate over the range of length(Z) - 2
for i in range(len(Z) - 2):
    # Slice Z to obtain a row of three elements and append to rows
    rows.append(Z[i:i+3])

# Convert list of rows to NumPy array
result = np.array(rows)

print("Two-dimensional array:")
print(result)

Two-dimensional array:
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [51]:
# Negate a boolean array inplace
bool_array = np.array([True, False, True])
bool_array[:] = np.logical_not(bool_array)

# Change the sign of a float array inplace
float_array = np.array([1.5, -2.7, 3.9])
float_array[:] *= -1

print("Negated boolean array:", bool_array)
print("Float array with changed sign:", float_array)

Negated boolean array: [False  True False]
Float array with changed sign: [-1.5  2.7 -3.9]


78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [52]:

def distance_to_line(P0, P1, p):
    # Vector from each point in P0 to p
    v = p - P0
    
    # Vector along each line segment from P0 to P1
    l = P1 - P0
    
    # Compute dot product
    dot_product = np.sum(v * l, axis=1)
    
    # Compute magnitude of l
    magnitude_l = np.linalg.norm(l, axis=1)
    
    # Compute cosine of angle
    cos_angle = dot_product / magnitude_l
    
    # Compute distance
    distance = np.abs(np.sqrt(np.linalg.norm(v, axis=1)**2 - cos_angle**2 * magnitude_l**2))
    
    return distance

# Example usage
P0 = np.array([[1, 1], [2, 3], [4, 5]])
P1 = np.array([[4, 5], [6, 7], [8, 9]])
p = np.array([3, 3])

distances = distance_to_line(P0, P1, p)
print("Distances to each line:", distances)

Distances to each line: [nan nan nan]


/tmp/ipykernel_800/3036045301.py:18: RuntimeWarning: invalid value encountered in sqrt
  distance = np.abs(np.sqrt(np.linalg.norm(v, axis=1)**2 - cos_angle**2 * magnitude_l**2))


79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [9]:
import numpy as np

def distance_point_to_line(P, P0, P1):
    """
    Compute the distance from each point P[j] to each line defined by points P0[i] and P1[i].
    
    Parameters:
    - P: A list of points P[j] where each point is a tuple (x, y).
    - P0: A list of points P0[i] where each point is a tuple (x, y).
    - P1: A list of points P1[i] where each point is a tuple (x, y).
    
    Returns:
    - A list of distances where each distance is a list of distances from each point P[j] to each line i.
    """
    # Convert lists to NumPy arrays for efficient computation
    P = np.array(P)
    P0 = np.array(P0)
    P1 = np.array(P1)
    
    # Initialize an empty list to store the distances
    distances = []
    
    # Iterate over each point P[j]
    for point in P:
        # Initialize an empty list to store the distances to each line
        point_distances = []
        
        # Iterate over each line defined by points P0[i] and P1[i]
        for i in range(len(P0)):
            # Compute the distance from the point to the line
            numerator = np.abs((P1[i,  1] - P0[i,  1]) * point[0] - (P1[i,  0] - P0[i,  0]) * point[1] + P1[i,  0] * P0[i,  1] - P1[i,  1] * P0[i,  0])
            denominator = np.sqrt((P1[i,  1] - P0[i,  1]) **  2 + (P1[i,  0] - P0[i,  0]) **  2)
            distance = numerator / denominator
            
            # Append the distance to the list of distances for the current point
            point_distances.append(distance)
        
        # Append the list of distances for the current point to the list of all distances
        distances.append(point_distances)
    
    return distances

# Example usage
P = [(1,  1), (2,  2), (3,  3)]
P0 = [(0,  0), (0,  0)]
P1 = [(1,  1), (2,  2)]

distances = distance_point_to_line(P, P0, P1)
print(distances)


[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]


80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)

In [54]:
import numpy as np

def extract_subpart(arr, shape, center, fill_value=0):
    # Calculate starting index for the subpart
    start_idx = np.maximum(center - np.array(shape) // 2, 0)
    
    # Calculate ending index for the subpart
    end_idx = start_idx + shape
    
    # Calculate the padding required for each dimension
    pad_before = np.abs(np.minimum(center - np.array(shape) // 2, 0))
    pad_after = np.maximum(end_idx - np.array(arr.shape), 0)
    
    # Pad the array with the fill value
    padded_arr = np.pad(arr, tuple(zip(pad_before, pad_after)), constant_values=fill_value)
    
    # Extract the subpart
    subpart = padded_arr[start_idx[0]:end_idx[0], start_idx[1]:end_idx[1]]
    
    return subpart

# Example usage
arr = np.random.randint(0, 10, size=(6, 6))
print("Original Array:")
print(arr)

shape = (3, 3)
center = (2, 2)
subpart = extract_subpart(arr, shape, center, fill_value=-1)
print("\nSubpart with shape (3, 3) centered at (2, 2):")
print(subpart)

Original Array:
[[6 3 9 1 9 7]
 [6 3 6 6 8 7]
 [7 0 3 5 3 8]
 [7 6 9 5 1 5]
 [6 8 5 3 0 6]
 [4 9 7 3 1 7]]

Subpart with shape (3, 3) centered at (2, 2):
[[3 6 6]
 [0 3 5]
 [6 9 5]]


81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [55]:
# Define array Z
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# Define the shape of R
shape_R = (4,)

# Create sliding window view of Z
view_Z = np.lib.stride_tricks.sliding_window_view(Z, shape_R)

# Convert the view to a list to obtain R
R = view_Z.tolist()

print(R)

[[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 12], [10, 11, 12, 13], [11, 12, 13, 14]]


82. Compute a matrix rank (★★★)

In [56]:
# Define your matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

print("Rank of the matrix:", rank)

Rank of the matrix: 2


83. How to find the most frequent value in an array?

In [57]:
# Example array
arr = np.array([1, 2, 3, 2, 2, 3, 4, 5, 6, 6, 6])

# Get unique elements and their counts
unique_values, counts = np.unique(arr, return_counts=True)

# Find the index of the maximum count
max_count_index = np.argmax(counts)

# Retrieve the most frequent value
most_frequent_value = unique_values[max_count_index]

print("The most frequent value:", most_frequent_value)

The most frequent value: 2


84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)


In [58]:
import numpy as np

# Create a random 10x10 matrix
matrix = np.random.randint(0, 10, (10, 10))

# Define the block size
block_size = 3

# Calculate the shape of the output array
output_shape = (matrix.shape[0] - block_size + 1, matrix.shape[1] - block_size + 1, block_size, block_size)

# Calculate the strides for the output array
strides = matrix.strides * 2

# Extract contiguous 3x3 blocks using stride_tricks.as_strided
blocks = np.lib.stride_tricks.as_strided(matrix, shape=output_shape, strides=strides)

print(blocks)

[[[[5 9 4]
   [1 7 2]
   [5 5 0]]

  [[9 4 2]
   [7 2 6]
   [5 0 7]]

  [[4 2 7]
   [2 6 7]
   [0 7 1]]

  [[2 7 9]
   [6 7 7]
   [7 1 0]]

  [[7 9 6]
   [7 7 9]
   [1 0 7]]

  [[9 6 4]
   [7 9 4]
   [0 7 1]]

  [[6 4 8]
   [9 4 1]
   [7 1 1]]

  [[4 8 8]
   [4 1 8]
   [1 1 9]]]


 [[[1 7 2]
   [5 5 0]
   [8 1 1]]

  [[7 2 6]
   [5 0 7]
   [1 1 4]]

  [[2 6 7]
   [0 7 1]
   [1 4 8]]

  [[6 7 7]
   [7 1 0]
   [4 8 8]]

  [[7 7 9]
   [1 0 7]
   [8 8 4]]

  [[7 9 4]
   [0 7 1]
   [8 4 8]]

  [[9 4 1]
   [7 1 1]
   [4 8 4]]

  [[4 1 8]
   [1 1 9]
   [8 4 1]]]


 [[[5 5 0]
   [8 1 1]
   [2 6 9]]

  [[5 0 7]
   [1 1 4]
   [6 9 5]]

  [[0 7 1]
   [1 4 8]
   [9 5 2]]

  [[7 1 0]
   [4 8 8]
   [5 2 3]]

  [[1 0 7]
   [8 8 4]
   [2 3 5]]

  [[0 7 1]
   [8 4 8]
   [3 5 9]]

  [[7 1 1]
   [4 8 4]
   [5 9 5]]

  [[1 1 9]
   [8 4 1]
   [9 5 2]]]


 [[[8 1 1]
   [2 6 9]
   [8 2 4]]

  [[1 1 4]
   [6 9 5]
   [2 4 2]]

  [[1 4 8]
   [9 5 2]
   [4 2 2]]

  [[4 8 8]
   [5 2 3]
   [2 2 0]]

  [[8 8 4]
   

85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [59]:

class SymmetricArray(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        return obj

    def __getitem__(self, index):
        i, j = index
        if isinstance(i, slice) or isinstance(j, slice):
            return super().__getitem__((i, j))
        else:
            return super().__getitem__((min(i, j), max(i, j)))

# Example usage:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

sym_arr = SymmetricArray(arr)
print(sym_arr[1, 2])  # Output: 6
print(sym_arr[2, 1])  # Output: 6

6
6


86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [10]:
import numpy as np

def sum_of_matrix_vector_products(matrices, vectors):
    """
    Compute the sum of the products of a set of matrices and vectors.
    
    Parameters:
    - matrices: A list of `p` matrices with shape `(n, n)`.
    - vectors: A list of `p` vectors with shape `(n,  1)`.
    
    Returns:
    - A vector with shape `(n,  1)` that is the sum of the products of the matrices and vectors.
    """
    # Convert lists to NumPy arrays for efficient computation
    matrices = np.array(matrices)
    vectors = np.array(vectors)
    
    # Compute the sum of the products of the matrices and vectors
    result = np.sum(matrices @ vectors, axis=0)
    
    return result

# Example usage
matrices = [np.array([[1,  2], [3,  4]]), np.array([[5,  6], [7,  8]])]
vectors = [np.array([[1], [2]]), np.array([[3], [4]])]

result = sum_of_matrix_vector_products(matrices, vectors)
print(result)


[[44]
 [64]]


87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [62]:

# Create a 16x16 array (example)
array_16x16 = np.random.randint(1, 10, size=(16, 16))

# Reshape the array into 4x4x4x4 blocks
blocks = array_16x16.reshape(4, 4, 4, 4)

# Sum the elements along the last two axes to get block sums
block_sums = np.sum(np.sum(blocks, axis=-1), axis=-1)

print(block_sums)

[[78 76 89 93]
 [96 71 79 80]
 [87 86 84 85]
 [76 78 60 86]]


88. How to implement the Game of Life using numpy arrays? (★★★)

In [63]:
def game_of_life(grid, iterations):
    for _ in range(iterations):
        neighbor_count = sum(np.roll(np.roll(grid, i, 0), j, 1)
                             for i in (-1, 0, 1) for j in (-1, 0, 1)
                             if (i != 0 or j != 0))
        grid = np.logical_or(np.logical_and(neighbor_count == 3, grid == 0),
                             np.logical_and(np.isin(neighbor_count, [2, 3]), grid == 1))
    return grid

# Example usage
initial_grid = np.random.choice([0, 1], size=(10, 10), p=[0.5, 0.5])  # Initialize random grid
final_grid = game_of_life(initial_grid, iterations=10)  # Run the Game of Life for 10 iterations

89. How to get the n largest values of an array (★★★)

In [64]:

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
n = 3
indices = np.argsort(arr)[-n:]
largest_values = arr[indices]

90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [65]:
# Define input vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5])
vector3 = np.array([6, 7, 8])

# Compute cartesian product
grid = np.meshgrid(vector1, vector2, vector3, indexing='ij')

# Flatten the arrays
cartesian_product = np.array([x.flatten() for x in grid]).T

91. How to create a record array from a regular array? (★★★)

In [66]:
# Define your regular array
regular_array = np.array([['John', 25], ['Alice', 30], ['Bob', 35]])

# Define the dtype for the record array
dtype = [('name', 'U10'), ('age', int)]

# Create the record array
record_array = np.rec.fromarrays(regular_array.T, dtype=dtype)

# Access elements of the record array
print(record_array['name'])
print(record_array['age'])

['John' 'Alice' 'Bob']
[25 30 35]


92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [67]:

# Define your large vector Z
Z = np.random.rand(1000000)  # Example vector of size 1,000,000

# Method 1: Using numpy.power function
Z_cubed_1 = np.power(Z, 3)

# Method 2: Using the ** operator
Z_cubed_2 = Z ** 3

# Method 3: Using numpy.multiply function twice
Z_cubed_3 = np.multiply(np.multiply(Z, Z), Z)

# Verify results
print(np.allclose(Z_cubed_1, Z_cubed_2))
print(np.allclose(Z_cubed_2, Z_cubed_3))

True
True


93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [11]:
import numpy as np

def find_matching_rows(A, B):
    """
    Find rows of array A that contain elements of each row of array B regardless of the order of the elements in B.
    
    Parameters:
    - A: A NumPy array of shape (8,  3).
    - B: A NumPy array of shape (2,  2).
    
    Returns:
    - A list of indices of rows in A that contain all elements of each row in B.
    """
    # Convert A and B to lists of sets for efficient comparison
    A_sets = [set(row) for row in A]
    B_sets = [set(row) for row in B]
    
    # Find rows of A that contain all elements of each row of B
    matching_rows = [i for i, a_set in enumerate(A_sets) if all(b_set.issubset(a_set) for b_set in B_sets)]
    
    return matching_rows

# Example usage
A = np.array([[1,  2,  3], [4,  5,  6], [7,  8,  9], [10,  11,  12], [13,  14,  15], [16,  17,  18], [19,  20,  21], [22,  23,  24]])
B = np.array([[1,  2], [3,  4]])

matching_rows = find_matching_rows(A, B)
print("Indices of matching rows in A:", matching_rows)


Indices of matching rows in A: []


94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [69]:
# Create a 10x3 matrix (example)
matrix = np.random.randint(0, 4, (10, 3))

# Find rows with unequal values
unequal_rows = matrix[np.apply_along_axis(lambda row: len(np.unique(row)) > 1, axis=1, arr=matrix)]

print("Rows with unequal values:")
print(unequal_rows)

Rows with unequal values:
[[2 0 0]
 [2 3 1]
 [3 2 3]
 [3 0 2]
 [1 0 0]
 [3 1 1]
 [3 0 1]
 [0 0 3]
 [1 1 0]
 [1 0 0]]


95. Convert a vector of ints into a matrix binary representation (★★★)

In [70]:
# Example vector of integers
vector = np.array([5, 10, 3, 7, 15])

# Convert each integer to binary representation
binary_matrix = np.array([list(np.binary_repr(num, width=8)) for num in vector])

print("Matrix of binary representation:")
print(binary_matrix)

Matrix of binary representation:
[['0' '0' '0' '0' '0' '1' '0' '1']
 ['0' '0' '0' '0' '1' '0' '1' '0']
 ['0' '0' '0' '0' '0' '0' '1' '1']
 ['0' '0' '0' '0' '0' '1' '1' '1']
 ['0' '0' '0' '0' '1' '1' '1' '1']]


96. Given a two dimensional array, how to extract unique rows? (★★★)

In [71]:
# Example 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [1, 2, 3],
                     [7, 8, 9]])

# Extract unique rows
unique_rows = np.unique(array_2d, axis=0)

print("Unique rows:")
print(unique_rows)

Unique rows:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [12]:
A = np.array([1,  2,  3])
B = np.array([4,  5,  6])

inner_product = np.einsum('i,i->', A, B)
print("Inner Product:", inner_product)

Inner Product: 32


98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [13]:
import numpy as np

def sample_path(X, Y, num_samples):
    """
    Sample a path described by two vectors X and Y using equidistant samples.
    
    Parameters:
    - X: A NumPy array representing the x-coordinates of the path.
    - Y: A NumPy array representing the y-coordinates of the path.
    - num_samples: The number of equidistant samples to generate.
    
    Returns:
    - A tuple of two NumPy arrays representing the x and y coordinates of the sampled path.
    """
    # Generate a sequence of evenly spaced values between the minimum and maximum values of X and Y
    x_samples = np.linspace(X.min(), X.max(), num_samples)
    y_samples = np.linspace(Y.min(), Y.max(), num_samples)
    
    # Interpolate the path using the sampled x and y values
    interpolated_X = np.interp(x_samples, X, X)
    interpolated_Y = np.interp(y_samples, Y, Y)
    
    return interpolated_X, interpolated_Y

# Example usage
X = np.array([1,  2,  3,  4,  5])
Y = np.array([2,  3,  4,  5,  6])
num_samples =  10

sampled_X, sampled_Y = sample_path(X, Y, num_samples)
print("Sampled X:", sampled_X)
print("Sampled Y:", sampled_Y)


Sampled X: [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
Sampled Y: [2.         2.44444444 2.88888889 3.33333333 3.77777778 4.22222222
 4.66666667 5.11111111 5.55555556 6.        ]


99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [74]:

def select_multinomial_rows(X, n):
    # Filter rows where all elements are integers and the sum equals n
    valid_rows = np.all(np.equal(np.mod(X, 1), 0), axis=1) & (np.sum(X, axis=1) == n)
    selected_rows = X[valid_rows]
    return selected_rows

# Example usage
X = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
n = 6
selected_rows = select_multinomial_rows(X, n)
print("Selected rows:", selected_rows)

Selected rows: [[1 2 3]]


100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [75]:

def bootstrap_confidence_interval(X, N):
    # Generate bootstrap samples
    bootstrap_means = [np.mean(np.random.choice(X, size=len(X), replace=True)) for _ in range(N)]
    
    # Compute percentiles for confidence interval
    lower_percentile = (100 - 95) / 2
    upper_percentile = 100 - lower_percentile
    lower_bound = np.percentile(bootstrap_means, lower_percentile)
    upper_bound = np.percentile(bootstrap_means, upper_percentile)
    
    return lower_bound, upper_bound

# Example usage
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
N = 1000  # Number of bootstrap samples
lower_bound, upper_bound = bootstrap_confidence_interval(X, N)
print("95% Confidence Interval for the mean:", (lower_bound, upper_bound))

95% Confidence Interval for the mean: (3.8, 7.3)
